import { readdirSync, readFileSync, writeFileSync } from "node:fs";
import { join, resolve } from "node:path";

import type { Plugin } from "vite";

export interface IpcGeneratorOptions {
    handlerDir: string;
    contractFile: string;
    typesFile: string;
    sharedTypesFile: string;
    runtimeFile: string;
}

function extractTypeKeys(file: string, typeName: string) {
    const content = readFileSync(file, "utf8");
    const marker = `export type ${typeName} = {`;
    const start = content.indexOf(marker);
    const end = content.indexOf("\n};", start + marker.length);
    if (start === -1 || end === -1) {
        throw new Error(`[IPC Gen] Expected ${typeName} to be a type literal in ${file}.`);
    }

    const keys: string[] = [];
    let braceDepth = 0;
    let parenthesisDepth = 0;
    for (const line of content.slice(start + marker.length, end).split(/\r?\n/)) {
        if (braceDepth === 0 && parenthesisDepth === 0) {
            const match = line.match(/^\s*"([^"]+)"\s*:/);
            if (match) {
                keys.push(match[1]);
            } else if (line.trim()) {
                throw new Error(
                    `[IPC Gen] ${typeName} may only contain quoted property signatures.`,
                );
            }
        }

        for (const character of line) {
            if (character === "{") braceDepth += 1;
            if (character === "}") braceDepth -= 1;
            if (character === "(") parenthesisDepth += 1;
            if (character === ")") parenthesisDepth -= 1;
        }
    }

    const duplicateKeys = keys.filter((key, index) => keys.indexOf(key) !== index);
    if (duplicateKeys.length > 0) {
        throw new Error(
            `[IPC Gen] ${typeName} contains duplicate channels: ${[...new Set(duplicateKeys)].sort((a, b) => a.localeCompare(b)).join(", ")}`,
        );
    }

    return keys.sort((a, b) => a.localeCompare(b));
}

function discoverChannels(handlerDir: string) {
    const handlerChannels = new Set<string>();
    const sendChannels = new Set<string>();

    for (const file of readdirSync(handlerDir).sort((a, b) => a.localeCompare(b))) {
        if (!file.endsWith(".ts")) continue;
        const content = readFileSync(join(handlerDir, file), "utf8");
        const handlerRegex = /\b(?:rh|ipcMain\.handle)\s*\(\s*["']([^"']+)["']/g;
        const sendRegex = /\bipcMain\.on\s*\(\s*["']([^"']+)["']/g;

        for (const match of content.matchAll(handlerRegex)) {
            const channel = match[1];
            if (handlerChannels.has(channel)) {
                throw new Error(`[IPC Gen] Duplicate handler channel: ${channel}`);
            }
            handlerChannels.add(channel);
        }
        for (const match of content.matchAll(sendRegex)) {
            sendChannels.add(match[1]);
        }
    }

    return {
        handlerChannels: [...handlerChannels].sort((a, b) => a.localeCompare(b)),
        sendChannels: [...sendChannels].sort((a, b) => a.localeCompare(b)),
    };
}

function toConstLiteral(values: string[]) {
    return `[\n${values.map((value) => `    ${JSON.stringify(value)}`).join(",\n")}\n] as const;`;
}

export function generateIpc(options: IpcGeneratorOptions) {
    const contractChannels = extractTypeKeys(options.contractFile, "IpcHandlers");
    const { handlerChannels, sendChannels } = discoverChannels(options.handlerDir);
    const missingHandlers = contractChannels.filter(
        (channel) => !handlerChannels.includes(channel),
    );
    const extraHandlers = handlerChannels.filter((channel) => !contractChannels.includes(channel));

    if (missingHandlers.length > 0 || extraHandlers.length > 0) {
        const details = [
            missingHandlers.length > 0
                ? `Missing handler channels: ${missingHandlers.join(", ")}`
                : null,
            extraHandlers.length > 0 ? `Extra handler channels: ${extraHandlers.join(", ")}` : null,
        ].filter((detail): detail is string => detail !== null);
        throw new Error(`[IPC Gen] Handler/contract channel mismatch.\n${details.join("\n")}`);
    }

    const typesContent = [
        "// This file is automatically generated by ipcGeneratorPlugin; do not edit it.",
        "",
        'export type { IpcHandlers } from "./ipc-contract";',
        "",
    ].join("\n");
    const eventChannels = extractTypeKeys(options.sharedTypesFile, "IpcEvents");
    const runtimeContent = [
        "// This file is automatically generated by ipcGeneratorPlugin; do not edit it.",
        "",
        `export const IPC_HANDLER_CHANNELS = ${toConstLiteral(handlerChannels)}`,
        "",
        `export const IPC_SEND_CHANNELS = ${toConstLiteral(sendChannels)}`,
        "",
        `export const IPC_EVENT_CHANNELS = ${toConstLiteral(eventChannels)}`,
        "",
        "export type IpcHandlerChannel = (typeof IPC_HANDLER_CHANNELS)[number];",
        "export type IpcSendChannel = (typeof IPC_SEND_CHANNELS)[number];",
        "export type IpcEventChannel = (typeof IPC_EVENT_CHANNELS)[number];",
        "",
    ].join("\n");

    writeIfChanged(options.typesFile, typesContent);
    writeIfChanged(options.runtimeFile, runtimeContent);
}

function writeIfChanged(file: string, content: string) {
    let currentContent: string | null = null;
    try {
        currentContent = readFileSync(file, "utf8");
    } catch {
        // The generated files do not exist on a fresh clone.
    }

    if (content === currentContent) return;
    writeFileSync(file, content);
    console.log(`[IPC Gen] Updated ${file}`);
}

export const ipcGeneratorPlugin = (): Plugin => {
    const options = {
        handlerDir: resolve("src/main/ipc/handlers"),
        contractFile: resolve("src/shared/ipc-contract.ts"),
        typesFile: resolve("src/shared/types.gen.ts"),
        sharedTypesFile: resolve("src/shared/types.ts"),
        runtimeFile: resolve("src/shared/ipc-keys.gen.ts"),
    };

    return {
        name: "ipc-generator",
        buildStart() {
            generateIpc(options);
        },
        configureServer(server) {
            server.watcher.on("change", (file) => {
                if (
                    file.includes(join("src", "main", "ipc", "handlers")) ||
                    file === options.contractFile ||
                    file === options.sharedTypesFile
                ) {
                    generateIpc(options);
                }
            });
        },
    };
};
