// This file is automatically generated by ipcGeneratorPlugin; do not edit it.

export const IPC_HANDLER_CHANNELS = [
    "download:create",
    "download:includeFile",
    "download:includeFolder",
    "download:list",
    "download:loadCollection",
    "download:openFolder",
    "download:pauseCollection",
    "download:pauseFile",
    "download:probeCollection",
    "download:remove",
    "download:resumeCollection",
    "download:resumeFile",
    "setting:getMany",
    "setting:set",
    "util:copyStr",
    "util:fs:metadata",
    "util:fs:mkdir",
    "util:fs:trash",
    "util:getAppStatus",
    "util:getClipboardFiles",
    "util:openCmd",
    "util:openExternal",
    "util:openPath",
    "util:showModal",
    "util:showOpenDialog",
    "window:syncTitleBarOverlay"
] as const;

export const IPC_SEND_CHANNELS = [

] as const;

export const IPC_EVENT_CHANNELS = [
    "download:item-update",
    "download:update",
    "fn:toast",
    "renderer:reload",
    "setting:update",
    "window:blur",
    "window:focus"
] as const;

export type IpcHandlerChannel = (typeof IPC_HANDLER_CHANNELS)[number];
export type IpcSendChannel = (typeof IPC_SEND_CHANNELS)[number];
export type IpcEventChannel = (typeof IPC_EVENT_CHANNELS)[number];
