
export type IpcHandlers = {
    // This section is automatically generated by ipcGeneratorPlugin; do not edit it.
    // IPC_HANDLERS_START
    "download:create": (payload: import("./types").CreateDownloadPayload) => Promise<import("./types").DownloadItem | null>;
    "download:includeFile": (...args: any[]) => any;
    "download:includeFolder": (...args: any[]) => any;
    "download:list": () => Promise<import("./types").DownloadItem[]>;
    "download:listZipEntries": (payload: import("./types").ListZipEntriesPayload) => Promise<import("./types").ListZipEntriesResult>;
    "download:loadCollection": (payload: import("./types").LoadCollectionPayload) => Promise<import("./types").Collection>;
    "download:openFolder": (id: string) => Promise<void>;
    "download:pauseCollection": (id: string) => Promise<void>;
    "download:pauseFile": (downloadId: string, fileId: string) => Promise<import("./types").DownloadItem | null>;
    "download:probeCollection": (payload: import("./types").ProbeCollectionPayload) => Promise<import("./types").ProbeCollectionResult>;
    "download:remove": (id: string) => Promise<void>;
    "download:resumeCollection": (id: string, options?: import("./types").ResumePayload) => Promise<void>;
    "download:resumeFile": (downloadId: string, fileId: string, options?: import("./types").ResumePayload) => Promise<import("./types").DownloadItem | null>;
    "setting:getMany": (keys?: readonly import("./settings").SettingKey[]) => Promise<Partial<import("./settings").AppSettings>>;
    "setting:set": (key: import("./settings").SettingKey, value: import("./settings").AppSettings[import("./settings").SettingKey]) => Promise<import("./settings").AppSettings[import("./settings").SettingKey]>;
    "upload:clearDraftSources": (...args: any[]) => any;
    "upload:copyLink": (collectionId: string) => Promise<void>;
    "upload:create": (payload: import("./types").CreateUploadPayload) => Promise<import("./types").UploadItem | null>;
    "upload:expandPaths": (paths: string[], maxFiles?: number) => Promise<import("./types").ExpandPathsResult>;
    "upload:list": () => Promise<import("./types").UploadItem[]>;
    "upload:pause": (collectionId: string) => Promise<void>;
    "upload:pauseFile": (...args: any[]) => any;
    "upload:pickFiles": (maxFiles?: number) => Promise<import("./types").ExpandPathsResult>;
    "upload:pickFolder": (maxFiles?: number) => Promise<import("./types").ExpandPathsResult>;
    "upload:remove": (collectionId: string) => Promise<void>;
    "upload:removeDraftSources": (...args: any[]) => any;
    "upload:resume": (collectionId: string, options?: { force?: boolean }) => Promise<void>;
    "upload:resumeFile": (...args: any[]) => any;
    "upload:solveTurnstile": () => Promise<string>;
    "util:copyStr": (...args: Parameters<typeof import("@main/service/util").copyStr>) => ReturnType<typeof import("@main/service/util").copyStr>;
    "util:fs:metadata": (...args: Parameters<typeof import("@main/service/util").getPathMetadata>) => ReturnType<typeof import("@main/service/util").getPathMetadata>;
    "util:fs:mkdir": (...args: Parameters<typeof import("@main/service/util").mkdir>) => ReturnType<typeof import("@main/service/util").mkdir>;
    "util:fs:trash": (...args: Parameters<typeof import("@main/service/util").trash>) => ReturnType<typeof import("@main/service/util").trash>;
    "util:getAppStatus": (...args: Parameters<typeof import("@main/service/util").getAppStatus>) => ReturnType<typeof import("@main/service/util").getAppStatus>;
    "util:getClipboardFiles": (...args: Parameters<typeof import("@main/service/util").getClipboardFiles>) => ReturnType<typeof import("@main/service/util").getClipboardFiles>;
    "util:openCmd": (...args: Parameters<typeof import("@main/service/util").openCmd>) => ReturnType<typeof import("@main/service/util").openCmd>;
    "util:openExternal": (...args: Parameters<typeof import("@main/service/util").openExternal>) => ReturnType<typeof import("@main/service/util").openExternal>;
    "util:openPath": (...args: Parameters<typeof import("@main/service/util").openPath>) => ReturnType<typeof import("@main/service/util").openPath>;
    "util:showModal": (...args: Parameters<typeof import("@main/service/util").showModal>) => ReturnType<typeof import("@main/service/util").showModal>;
    "util:showOpenDialog": (...args: Parameters<typeof import("@main/service/util").showOpenDialog>) => ReturnType<typeof import("@main/service/util").showOpenDialog>;
    "window:syncTitleBarOverlay": (options: import("./types").TitleBarOverlaySyncOptions) => void;
    // IPC_HANDLERS_END
};
